version: 2.1
jobs:
  build:
    working_directory: ~/circleci-demo-python
    docker:
      - image: circleci/python:3.6.4 # primary container for the build job
    steps:
        - checkout  # checkout source code to working directory
        - run: 
            command: |
              pipenv run python ex01.py test
        - store_test_results:
            path: test-results
        - store_artifacts: #บันทึกผลลัพธ์การทดสอบ
            path: test-results
            destination: tr1