version: 2.1
jobs:
  build:
    working_directory: ~/circleci-demo-python
    docker:
      - image: circleci/python:3.6.4
    steps:
        - run: 
            command: |
              python ./ex01.py test
            